app:
  mode: DEV
  version: ${pom.version}
  mongo:
    url: mongodb://localhost/hellocinedb
    writeResultChecking: EXCEPTION   #NONE, LOG, EXCEPTION
  bugSnag: 16f3943bcff62960d25dcf14053efb98
  graphite:
    activate: false
    apiKey: c68abc3f-0356-4f5e-a0c3-062db5ae697b
    host: carbon.hostedgraphite.com
    port: 2003
  client:
    readTimeOut: 20000
    connectTimeout: 5000
    activateMetrics: true
    userAgent: Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5
#endpoints:
#  beans:
#    id: beans
#    sensitive: true
#    enabled: true
#  jolokia:
#    enabled: true
#info:
#  build:
#   artifact: ${project.artifactId}
#    name: ${project.name}
#    description: ${project.description}
#    version: ${project.version}
#security:
#  user:
#    name: super
#    password: secret
#    role: SUPERUSER
management:
  context-path: /manage
  #security:
  #  role: SUPERUSER

jolokia:
  config:
    debug: true